# SrvStartupNotice by l1ratch
# More detailed: https://github.com/l1ratch/SrvStartupNotice

botToken: "Telegram_BotToken"
chatId: "Telegram_ChatID"
serverId: "(ServerName)"

serverEnable: "The Minecraft server has turned on!"
serverDisable: "The Minecraft server is shutting down..."
